name: melkalk
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^1.3.1
#  google_mobile_ads: ^0.13.6
  flutter_yandex_mobile_ads: ^0.0.9
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#0277bd"
  image: assets/splashnew.png
  android: true
  ios: true

  # color: "#ffffff"
  # image: assets/splash_full.png
  # color_dark: "#1a1a1a"
  # image_dark: assets/splash_full.png
  # android: true
  # ios: true
  # android_gravity: fill
  # ios_content_mode: scaleAspectFill